//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPEnhancedEntryView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPEnhancedEntryView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Attach {
            get {
                object obj = ResourceManager.GetObject("B16x16_Attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Browser {
            get {
                object obj = ResourceManager.GetObject("B16x16_Browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_DeleteEntry {
            get {
                object obj = ResourceManager.GetObject("B16x16_DeleteEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_EditDelete {
            get {
                object obj = ResourceManager.GetObject("B16x16_EditDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Yellow_Open {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Yellow_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Key_New {
            get {
                object obj = ResourceManager.GetObject("B16x16_Key_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Import {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Info {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Sign {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B17x05_3BlackDots {
            get {
                object obj = ResourceManager.GetObject("B17x05_3BlackDots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy {0}.
        /// </summary>
        internal static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected attachment?.
        /// </summary>
        internal static string DeleteAttachmentQuestion {
            get {
                return ResourceManager.GetString("DeleteAttachmentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected attachments?.
        /// </summary>
        internal static string DeleteAttachmentsQuestion {
            get {
                return ResourceManager.GetString("DeleteAttachmentsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attachments.
        /// </summary>
        internal static string DeleteAttachmentsTitle {
            get {
                return ResourceManager.GetString("DeleteAttachmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attachment.
        /// </summary>
        internal static string DeleteAttachmentTitle {
            get {
                return ResourceManager.GetString("DeleteAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide Empty Standard Fields.
        /// </summary>
        internal static string HideEmptyStandardFieldsOptionMenuItem {
            get {
                return ResourceManager.GetString("HideEmptyStandardFieldsOptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more attachments.
        /// </summary>
        internal static string MoreAttachments {
            get {
                return ResourceManager.GetString("MoreAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the field &apos;{0}&apos; from all selected entries?.
        /// </summary>
        internal static string MultipleEntryFieldDeleteQuestion {
            get {
                return ResourceManager.GetString("MultipleEntryFieldDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set the value of the field &apos;{0}&apos; on all selected entries?.
        /// </summary>
        internal static string MultipleEntryFieldSetValueQuestion {
            get {
                return ResourceManager.GetString("MultipleEntryFieldSetValueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Values.
        /// </summary>
        internal static string MultipleValues {
            get {
                return ResourceManager.GetString("MultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MultpleEntryFieldSetValueCommand {
            get {
                return ResourceManager.GetString("MultpleEntryFieldSetValueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (add new).
        /// </summary>
        internal static string NewFieldRowName {
            get {
                return ResourceManager.GetString("NewFieldRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Entry View Options.
        /// </summary>
        internal static string OptionsMenuItem {
            get {
                return ResourceManager.GetString("OptionsMenuItem", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Reveal {
            get {
                object obj = ResourceManager.GetObject("Reveal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RevealGrey {
            get {
                object obj = ResourceManager.GetObject("RevealGrey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
